### ISSUE TITLE
type integer has no method `at`

### ISSUE THREAD

**Issue by siainbuletin** [0rphee/derive-it#1]
Hi! Love the package, it's just what I needed for my logic classes. Everything worked fine until I wanted to compile my document once and started getting this error:

```
error: type integer has no method `at`
   ┌─ @preview/derive-it:0.1.1/lib.typ:15:31
   │
15 │   let hasDependencies = if arr.at(0).len() == 4 {true} else {false}
   │
```

Error message is generated when running `typst watch` on the document.

**Comment by 0rphee** [comment]
Hi! could you share your code calling the function? 

Both `ded-nat` and `ded-nat-boxed` are designed to receive an array of items with the shape of:
- either `("text", int, "text", "text)` 
- or `(int, "text", "text")`

```typ
#ded-nat(stcolor: black, arr:(
    ("1", 0, $forall x (P x) and forall x (Q x)$, "PR"),
    ("2", 0, $forall x (P x -> R x)$, "PR"),
 ))

#ded-nat(stcolor: black, arr:(
    (0, $forall x (P x) and forall x (Q x)$, "PR"),
    (0, $forall x (P x -> R x)$, "PR"),
 ))
```

The previous code renders this:
<img width="232" alt="Screenshot 2024-12-01 at 12 12 42 p m" src="https://github.com/user-attachments/assets/6f8e9873-5f9d-4d4e-86f4-1cad884f5186">

**Comment by siainbuletin** [comment]
I've checked all of the `nat-ded` environments I inserted in my document and none contain errors.

This is an example of one such environment:

```typst
#ded-nat(
  stcolor: black,
  arr:(
    ("1", 0, $A -> B$, "Premiză"),
    ("2", 0, $A$, "Asumpție"),

    ("1, 2", 0, $B$, $1, 2 E ->$),
    ("4", 0, $C$, "Asumpție"),
    
    ("2, 4", 0, $A \& C$, $2, 4 I \&$),
    ("1, 2, 4", 0, $B \& C$, $3, 4 I \&$),

    ("1, 2, 4", 0, $(A \& C) -> (B \& C)$, $5, 6 I ->$)
  )
```

Was thinking maybe the dependencies on the very left are the issue. I have to reiterate that the document stopped compiling _randomly_ as I was writing and adding new sections to the document. All unfinished natural deduction proofs are commented out to prevent compilation errors.

**Comment by 0rphee** [comment]
Hmm... this is very weird. each `#ded-nat`call is self contained, so there's no reason for one call to affect the others (your example lacks a ')' btw, I still tried to call use it multiple times and it worked fine.)

If it is possible, would you be able to share the whole document? or at least all calls to `ded-nat`?

> ```typ
> error: type integer has no method `at`
>    ┌─ @preview/derive-it:0.1.1/lib.typ:15:31
>    │
> 15 │   let hasDependencies = if arr.at(0).len() == 4 {true} else {false}
>    │
> ```
This error is caused because the array you input has an integer instead of an array, so my guess is that in one of your calls, instead of calling the function like this:

```typ
#ded-nat(stcolor: black, arr:(
    (0, $forall x (P x) and forall x (Q x)$, "PR"),
    (0, $forall x (P x -> R x)$, "PR")
 ))
```

(Maybe) You called it like this (notice the lack of an additional pair of parentheses):
```typ
#ded-nat(stcolor: black, arr:
    (0, $forall x (P x) and forall x (Q x)$, "PR"),
    (0, $forall x (P x -> R x)$, "PR")
)
```

**Comment by siainbuletin** [comment]
I checked everything again, indeed one of the parantheses was missing in a subdocument. I wasn't getting any errors within the document and couldn't figure out where the mistake was at all. Fortunately now the document can compile again. Thank you for your help!

**Comment by 0rphee** [comment]
No problem! If you have any usability suggestions or something like that please tell me :)
